# The format that will be displayed by placeholders
placeholder-format: "(%pronouns%)"

# Whether players must request pronouns to be added
require-approval: false

messages:
  pronouns-set: "Your pronouns have been set to '%pronouns%'"
  pronouns-char-limit: "Pronouns cannot exceed 24 characters"
  check-pronouns: "%player%'s pronouns are '%pronouns%'"
  check-pronouns-none: "%player% has not set any pronouns"
  preferred-name-set: "Your preferred name have been set to '%preferred_name%'"
  preferred-name-char-limit: "Preferred names cannot exceed 12 characters"
  check-preferred-name: "%player%'s preferred name is '%preferred_name%'"
  check-preferred-name-none: "%player% has not set a preferred name"
  invalid-command: "Invalid command format, try %command%"
  failed-to-set: "Failed to set preferences, please try again later!"
  player-not-online: "Could not find player '%s' online"
  reloaded: "&#b7faa2SimplyPronouns has been reloaded &#66b04f🔃"