name: SimplyPronouns
version: '${version}'
main: org.lushplugins.simplypronouns.SimplyPronouns
api-version: '1.20'
authors:
  - OakLoaf
commands:
  simplypronouns:
    usage: /simplypronouns
  pronouns:
    usage: /pronouns <pronouns>
  checkpronouns:
    usage: /checkpronouns <player>
  preferredname:
    usage: /preferredname <name>
  checkpreferredname:
    aliases:
      - checkname
    usage: /checkpreferredname <player>
softdepend:
  - PlaceholderAPI